# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmBudget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBudget(object):
    def setupUi(self, AddBudget):
        AddBudget.setObjectName("AddBudget")
        AddBudget.resize(520, 604)
        self.btnOkCnacel = QtWidgets.QDialogButtonBox(AddBudget)
        self.btnOkCnacel.setGeometry(QtCore.QRect(150, 520, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnOkCnacel.setFont(font)
        self.btnOkCnacel.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Ok)
        self.btnOkCnacel.setObjectName("btnOkCnacel")
        self.txtNote = QtWidgets.QTextEdit(AddBudget)
        self.txtNote.setGeometry(QtCore.QRect(140, 390, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.txtNote.setFont(font)
        self.txtNote.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.txtNote.setObjectName("txtNote")
        self.lblBudget = QtWidgets.QLabel(AddBudget)
        self.lblBudget.setGeometry(QtCore.QRect(90, 100, 60, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblBudget.setFont(font)
        self.lblBudget.setStyleSheet("Color:rgb(0, 255, 0)")
        self.lblBudget.setObjectName("lblBudget")
        self.lblNote = QtWidgets.QLabel(AddBudget)
        self.lblNote.setGeometry(QtCore.QRect(60, 410, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblNote.setFont(font)
        self.lblNote.setStyleSheet("Color:rgb(0, 255, 0)")
        self.lblNote.setObjectName("lblNote")
        self.lblAmount = QtWidgets.QLabel(AddBudget)
        self.lblAmount.setGeometry(QtCore.QRect(90, 170, 67, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblAmount.setFont(font)
        self.lblAmount.setStyleSheet("color:rgb(85, 255, 0)")
        self.lblAmount.setObjectName("lblAmount")
        self.lblSpent = QtWidgets.QLabel(AddBudget)
        self.lblSpent.setGeometry(QtCore.QRect(90, 240, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblSpent.setFont(font)
        self.lblSpent.setStyleSheet("Color:rgb(0, 255, 0)")
        self.lblSpent.setObjectName("lblSpent")
        self.lblPeriod = QtWidgets.QLabel(AddBudget)
        self.lblPeriod.setGeometry(QtCore.QRect(90, 310, 54, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblPeriod.setFont(font)
        self.lblPeriod.setStyleSheet("Color:rgb(0, 255, 0)")
        self.lblPeriod.setObjectName("lblPeriod")
        self.txtAmount = QtWidgets.QLineEdit(AddBudget)
        self.txtAmount.setGeometry(QtCore.QRect(200, 170, 161, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.txtAmount.setFont(font)
        self.txtAmount.setStyleSheet("font: 12pt \"Arial\";\n"
"font: 12pt \"Segoe UI\";")
        self.txtAmount.setObjectName("txtAmount")
        self.txtSpent = QtWidgets.QLineEdit(AddBudget)
        self.txtSpent.setGeometry(QtCore.QRect(200, 240, 161, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.txtSpent.setFont(font)
        self.txtSpent.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.txtSpent.setText("")
        self.txtSpent.setObjectName("txtSpent")
        self.lblNewBudget = QtWidgets.QLabel(AddBudget)
        self.lblNewBudget.setGeometry(QtCore.QRect(170, 30, 201, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.lblNewBudget.setFont(font)
        self.lblNewBudget.setStyleSheet("\n"
"font: 20pt \"MV Boli\";\n"
"color:rgb(170, 0, 255)\n"
"\n"
"")
        self.lblNewBudget.setObjectName("lblNewBudget")
        self.txtPeriod = QtWidgets.QLineEdit(AddBudget)
        self.txtPeriod.setGeometry(QtCore.QRect(200, 310, 161, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.txtPeriod.setFont(font)
        self.txtPeriod.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.txtPeriod.setObjectName("txtPeriod")
        self.txtBudget = QtWidgets.QLineEdit(AddBudget)
        self.txtBudget.setGeometry(QtCore.QRect(200, 100, 161, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.txtBudget.setFont(font)
        self.txtBudget.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.txtBudget.setObjectName("txtBudget")

        self.retranslateUi(AddBudget)
        QtCore.QMetaObject.connectSlotsByName(AddBudget)

    def retranslateUi(self, AddBudget):
        _translate = QtCore.QCoreApplication.translate
        AddBudget.setWindowTitle(_translate("AddBudget", "Form"))
        self.lblBudget.setText(_translate("AddBudget", "Budget"))
        self.lblNote.setText(_translate("AddBudget", "Note"))
        self.lblAmount.setText(_translate("AddBudget", "Amount"))
        self.lblSpent.setText(_translate("AddBudget", "Spent"))
        self.lblPeriod.setText(_translate("AddBudget", "Period"))
        self.lblNewBudget.setText(_translate("AddBudget", "New Budget "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddBudget = QtWidgets.QWidget()
    ui = Ui_AddBudget()
    ui.setupUi(AddBudget)
    AddBudget.show()
    sys.exit(app.exec_())
